version: "2"
services:
  elasticsearch:
    container_name: elasticsearch
    build: ./elasticsearch/
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

#  logstash:
#    container_name: logstash
#    build: ./logstash/
#    command: -f /etc/logstash/conf.d/
#    volumes:
#      - ./logstash/config:/etc/logstash/conf.d
#    ports:
#      - "9999:9999"
#    links:
#      - elasticsearch
#
  kibana:
    container_name: kibana
    build: ./kibana/
    volumes:
      - ./kibana/config/:/opt/kibana/config/
    ports:
      - "5601:5601"
    links:
      - elasticsearch
