version: "3"
services:

#  client:
#    image: 'node:latest'
#    volumes:
#      - './client:/home/node/app'
#    working_dir: /home/node/app/client
#    ports:
#      - "4200:4200"
#    command:
#      - /bin/sh
#      - '-c'
#      - 'npm install && npm install -g @angular/cli@1.7.1 && ng serve --host 0.0.0.0'

  client:
    image: nadjim/elastic-client
    container_name: client
    ports:
      - "8080:80"

  elasticsearch:
    container_name: elasticsearch
    build: ./elasticsearch/
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  kibana:
    container_name: kibana
    build: ./kibana/
    volumes:
      - ./kibana/config/:/opt/kibana/config/
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

